const competitorList = [
	// { name: 'Leighton Brack', number: 1, racing: false },
	// { name: 'Derek Brown', number: 2, racing: false },
	// { name: 'Rachel Darling Love', number: 3, racing: false },
	// { name: 'Paul Reed', number: 4, racing: false },
	// { name: 'Dawn Oades', number: 5, racing: false },
	// { name: 'Chris Wiles', number: 6, racing: false },
	// { name: 'Sue Taft', number: 7, racing: false },
	// { name: 'Neil Adams', number: 8, racing: false },
	// { name: 'Nick Dailey', number: 9, racing: false },
	// { name: 'Adeline Brack', number: 10, racing: false },
	// { name: 'Chris Nation', number: 11, racing: false },
	// { name: 'John Route', number: 12, racing: false },
	// { name: 'Chris Birkett', number: 13, racing: false },
	// { name: 'Shelly Hindley', number: 14, racing: false },
	// { name: 'Charlie Robinson', number: 15, racing: false },
	// { name: 'Chris Ellerston', number: 16, racing: false },
	// { name: 'Adrian Messingham', number: 17, racing: false },
	// { name: 'Glenn Halsey', number: 18, racing: false },
	// { name: 'Dave Fletcher', number: 19, racing: false },
	// { name: 'Robert Fletcher', number: 20, racing: false },
	// { name: 'Kirsty Drakeford', number: 21, racing: false },
	// { name: 'Amy Aistrop', number: 22, racing: false },
	// { name: 'Amanda Dean', number: 23, racing: false },
	// { name: 'Dinah Ashbridge', number: 24, racing: false },
	// { name: 'Andy Naylor', number: 25, racing: false },
	// { name: 'Paul Ridpath', number: 26, racing: false },
	// { name: 'Andy Leahom', number: 27, racing: false },
	// { name: 'Daniel Scott', number: 28, racing: false },
	// { name: 'James Godfrey', number: 29, racing: false },
	// { name: 'Finlay Godfrey', number: 30, racing: false },
	// { name: 'Dave Maskell', number: 31, racing: false },
	// { name: 'Pete Young', number: 32, racing: false },
	// { name: 'Stephen Bolton', number: 33, racing: false },
	// { name: 'Michelle Hillaby', number: 34, racing: false },
	// { name: 'Ken Pearson', number: 35, racing: false },
	// { name: 'Jacqui Ker', number: 36, racing: false },
	// { name: 'Darren Atkinson', number: 37, racing: false },
	// { name: 'Ben Atkinson', number: 38, racing: false },
	// { name: 'Richard Stone', number: 39, racing: false },
	// { name: 'Paul Wilkinson', number: 40, racing: false },
	// { name: 'Leanne Kilvington', number: 41, racing: false },
	// { name: 'Naomi Drakeford', number: 42, racing: false },
	// { name: 'Mark Padley', number: 43, racing: false },
	// { name: 'Luke Davison', number: 44, racing: false },
	// { name: 'Simon Pick', number: 45, racing: false },
	// { name: 'Alan Bayston', number: 46, racing: false },
	// { name: 'Jason Kenning', number: 47, racing: false },
	// { name: 'Jo Brown', number: 48, racing: false },
	// { name: 'Carl Horth', number: 49, racing: false },
	// { name: 'Graham Justice', number: 50, racing: false },
	// { name: 'Susie Gibson', number: 51, racing: false },
	// { name: 'Robin Rowlin', number: 52, racing: false },
	// { name: 'Ellen Messingham', number: 53, racing: false },
	// { name: 'Danielle Prentice', number: 54, racing: false },
	// { name: 'Jon Dawson', number: 55, racing: false },
	// { name: 'Lisa Douglas', number: 56, racing: false },
	// { name: 'Ben Birtles', number: 57, racing: false },
	// { name: 'Mark Gronow', number: 58, racing: false },
	// { name: 'Dave Wood', number: 59, racing: false },
	// { name: 'Jim Hyam', number: 60, racing: false },
	// { name: 'Sue Forester', number: 61, racing: false },
	// { name: 'Pam Edgar', number: 62, racing: false },
	// { name: 'Andy Smith', number: 63, racing: false },
	// { name: 'James Bray', number: 64, racing: false },
	// { name: 'Declan Chambers', number: 65, racing: false },
	// { name: 'Steve Hawtree', number: 66, racing: false },
	// { name: 'Dave Burnott', number: 67, racing: false },
	// { name: 'Jonathan York', number: 68, racing: false },
	// { name: 'Jamie Hilton', number: 69, racing: false },
	// { name: 'Charlotte Shermai', number: 70, racing: false },
	// { name: 'Richard North', number: 71, racing: false },
	// { name: 'Gaynor Sidard', number: 72, racing: false },
	// { name: 'Natalie Angelopoulos', number: 73, racing: false },
	// { name: 'Russ Smith', number: 74, racing: false },
	// { name: 'Steve Braun', number: 75, racing: false },
	// { name: 'Pawel Zurek', number: 76, racing: false },
	// { name: 'Jill Speight', number: 77, racing: false },
	// { name: 'Matt Farrier', number: 78, racing: false },
];

export default competitorList;

export function setCompetitors(data) {
	competitorList = data;
}
